### ISSUE TITLE
InboxBox/BubbleBox Support

### ISSUE THREAD

**Issue by Talento90** [asennikov/ember-g-map#105]
First of all thanks for this great component! 👍 

I would like to know if you are planning to support `infobox` or `bubblebox`? At the moment it's very hard to customize the `infowindow` css. I am trying to remove the X button and some width and height are automatically calculated! :/

**Comment by steveszc** [comment]
Adding support for 3rd party google map plugins is outside the scope of this addon, but should be relatively straight forward to implement in your own component. You could write your own `g-map-infobox` or `g-map-bubblebox` component that could mirror the `g-map-infowindow` component api but replace infowindow with infobox or bubblebox. Something like that could also be turned into an addon, similar to how `ember-leaflet` handles addons.

**Comment by Talento90** [comment]
I did what you said, basically I copied the `infowindow` component and I changed this: 
```
      const infowindow = new InfoBox({
        content: this.get('element')
      });
```
It's rendering correctly and do not throw any errors but the problem is that I am losing all ember stuff like events or route links. Do you know which problem can be?

Thanks!
