### ISSUE TITLE
map not loading from address only static lat and long

### ISSUE THREAD

**Issue by briemarie** [asennikov/ember-g-map#112]
I have been attempting to use this plugin all day, but am having no success using it dynamically.
If I specify lat and long coordinates directly, the map loads correctly. Using the places library to dynamically load maps from addresses is not working though.

- I have checked in my Google API console and can see that both Google Places API and Google Maps API are receiving requests and returning no errors.
- The issue is not the variables being passed in as I have tested by setting the address statically, for example `address="San Jose, California"`
- I have tried both 'live' and 'init' for the markersFitMode
- The console is returning no errors and ember server is returning no errors

Here are the screen shots of how I am loading the g-map, the blank canvas that is returned (shows a map when lat and long are set though), and what my Google API Console looks like.
![screen shot 2017-06-19 at 5 56 12 pm](https://user-images.githubusercontent.com/8213949/27312068-69bd4e14-551a-11e7-8b99-d84bcf043a54.png)
![screen shot 2017-06-19 at 5 56 42 pm](https://user-images.githubusercontent.com/8213949/27312075-794e0ca6-551a-11e7-95f9-4955ce7a98d5.png)
![screen shot 2017-06-19 at 6 01 14 pm](https://user-images.githubusercontent.com/8213949/27312076-7f526b38-551a-11e7-848a-4b60515856af.png)

**Comment by jeffrey008** [comment]
Have you required the library?
```javascript
// environment.js
ENV['g-map'] = {
  libraries: ['places']
}
```

**Comment by briemarie** [comment]
Yes

**Comment by steveszc** [comment]
@briemarie
Try this:
`{{#g-map-address-marker context address=(concat asset.address.locality ', ' asset.address.province) as |markerContext|}}`

Or  
`{{#g-map-address-marker context address=computedAddress as |markerContext|}}`
where `computedAddress` is a computed property.

In your example you are trying to use double curlies to declare the address property, which is invalid syntax for passing properties into a component.

**Comment by steveszc** [comment]
Closing. If the above suggestions don't solve the issue please let me know and I can reopen.

**Comment by briemarie** [comment]
Thank you for the suggestions, I'll be sure to get the address down to a single property, however the property evaluation isn't the issue here. I tested out static city and state (San Jose, California) and city and country (Sydney, Australia) combinations in the address and got the same empty map results. The only way I was able to get a map was with lat and long coordinates.

**Comment by steveszc** [comment]
My apologies, I mistook your original post to mean that it was working with the static city/state.
Have you been able to get a map to render at all (without the address marker)? 

Can you double check that you added the CSS styles for the g-map-canvas (per the README). If those styles are there, you might also try adding a lat/lng to the `g-map` itself. Also, try copy/pasting the `g-map-address-marker` example from the readme and see if you can get that to work.

I set up a test repo last night and had an address marker working using the examples from the readme.

**Comment by briemarie** [comment]
The example from the README loads a map with a marker dropped on Russian Hill in SF. If I change the address to another city though (Sydney, Australia for example), the map still loads on San Francisco, but no marker is set (which is obviously coming from the lat and lng that is still set on the g-map component). 

If I remove the lat and lng and replace with markersFitMode (which is what I need since I need the marker and the lat and long coordinates to get set dynamically based on the address that loads with the modal), the map does not load at all. Am I misunderstanding how setting the address is supposed to work with places to dynamically generate the lat and long coordinates?

Thanks for all your help!

**Comment by briemarie** [comment]
Ok, this ticket can be closed. Thank you for all of your help. 

Aside from the markersFitMode='init' still not working, I have successfully gotten the map to load on the correct address so long as I provide a valid full address (street, city, state). Any of those address pieces alone are not accurate, but I suppose that is to be expected. 

One shortcoming I do see though is that if the street address is incorrect but the city and state are valid, the map fails to load altogether instead of loading the city and state.

**Comment by steveszc** [comment]
Thanks, glad you got it figured out.
