### ISSUE TITLE
Markers are not showing

### ISSUE THREAD

**Issue by bttf** [asennikov/ember-g-map#119]
I have the following code, but no markers. I tried zooming out as well. Not sure what's wrong here. Am I missing something?

```
    {{#g-map
      lat=lat
      lng=lng
      zoom=12
      as |context|
    }}
      {{#each spaces as |space|}}
        {{g-map-marker context lat=space.latitutde lng=space.longitude}}
      {{/each}}
    {{/g-map}}
```

**Comment by Mithrilhall** [comment]
Can you recreate the problem in a [Twiddle](https://ember-twiddle.com/)?

**Comment by steveszc** [comment]
You have a typo {{g-map-marker context lat=space**.latitutde** lng=space.longitude}}

**Comment by bttf** [comment]
I don't think I'll ever live down the shame. Thank you
