### ISSUE TITLE
Add panControl, zoomControl, mapTypeControl, streetViewControl, mapTypeId, scrollwheel

### ISSUE THREAD

**Issue by pohodnya** [asennikov/ember-g-map#120]
Can you add some properties to your component? 
panControl: true/false
zoomControl: true/false
mapTypeControl: true/false
streetViewControl: true/false
mapTypeId: 'roadmap', satellite', 'hybrid', 'terrain'
scrollwheel: true/false

**Comment by steveszc** [comment]
Any of these options can be added to an options object and passed into the `g-map` component via the `options` property.
