### ISSUE TITLE
Geolocation Support?

### ISSUE THREAD

**Issue by jayvarner** [asennikov/ember-g-map#122]
Thanks for all the work here. This addon works great.

Is there any interest in adding support to [display a user's or device's position](https://developers.google.com/maps/documentation/javascript/geolocation)? I'm happy to make a PR with my fork that adds a [g-map-geolocation](https://github.com/jayvarner/ember-g-map/blob/feature/geolocation/addon/components/g-map-geolocation.js) component. It simply extends `g-map-marker` and overrides `setPosition()` to plot the lat/lng from `navigator.geolocation()`.

As it extends `g-map-marker`, you can pass all the same options, e.g. custom icon.

It's still a WIP. I've only spent a few hours on it. I need to write some unit tests. I haven't played with all the options.

I would also like to add a service to track if someone has declined to share their location, or that their browser does not support it. That way, one could display a message explaining why a feature that depends on knowing their location is unavailable.

Again, thanks for all the work here. It's really helping me out.

**Comment by steveszc** [comment]
I like the idea (its a use case I've worked on in my app at work), but I think the geolocation/navigator functionality belongs in a service, and at that point it creeps beyond the scope of this add-on. 

There are already other add-ons that cover the geolocation API (ex. https://github.com/igorpreston/ember-cli-geo), and its pretty straightforward to wire that up to a g-map-marker component.

I'm open to hearing other opinions, but I think this kind of thing ought to be kept separate.

I'm going to close for now, but I'll reopen if more discussion is needed.
