### ISSUE TITLE
Zoom Level on "Markers bound to address query"

### ISSUE THREAD

**Issue by mansona** [asennikov/ember-g-map#15]
I'm trying to use the [Markers bound to address query](https://github.com/asennikov/ember-g-map#marker-bound-to-address-query) feature and I would really like the zoom level to stay fixed even when I update the search query

Here is how i'm using it: 

```
{{paper-input label="Address" value=address}}
{{#g-map markersFitMode='live' zoom=12 as |context|}}
  {{g-map-address-marker context address=address}}
{{/g-map}}
```

I have the address bound to an input but I would really like it to stay at a set zoom level when I search for a new address. What is the best way to do this?

**Comment by asennikov** [comment]
Needs some research on this, since `markersFitMode='live'` forces map to be fit to markers on every change. And by fit I mean calling `fitBounds` method of `google.maps.Map` object which sets zoom  by itself.

Probably I can add option to reset zoom back after each `fitBounds` call, but it may result in some ugly flickering.

**Comment by thoresuenert** [comment]
the solution is to use the geometry viewport if present for single markers.
it is in the autocomplete places example here: [Places Autocomplete Example](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete)

`js 
// If the place has a geometry, then present it on a map.
          if (place.geometry.viewport) {
            map.fitBounds(place.geometry.viewport);
          } else {
            map.setCenter(place.geometry.location);
            map.setZoom(17);  // Why 17? Because it looks good.
          }
          marker.setPosition(place.geometry.location);
          marker.setVisible(true);
`
