### ISSUE TITLE
Getting the latitude and longitude out of a marker in the map

### ISSUE THREAD

**Issue by mansona** [asennikov/ember-g-map#16]
I'm creating a bit of a make shift search by binding an input field with the address of a `{{g-map-address-marker}}`

```
{{paper-input label="Address" value=address}}
{{#g-map markersFitMode='live' zoom=12 as |context|}}
  {{g-map-address-marker context address=address}}
{{/g-map}}
```

I'm wondering once it is using the right place how do I get the marker details out of the `{{g-map-address-marker}}` so I can save the lat long on my model and put it in the database?

**Comment by asennikov** [comment]
I guess I can add an optional action for this, to let your application receive lat/lng data back.
So it could be something like:
```
{{paper-input label="Address" value=address}}
{{#g-map markersFitMode='live' zoom=12 as |context|}}
  {{g-map-address-marker context address=address onLocationChange=(action "saveToDatabase")}}
{{/g-map}}
```

**Comment by asennikov** [comment]
@mansona could you take a look at https://github.com/asennikov/ember-g-map/pull/22? Does it cover you case?

**Comment by mansona** [comment]
@asennikov yes that looks like it should cover my use case for this :+1: do you want me to pull the branch and test it? I notice you already have tests so that's why I'm asking

**Comment by asennikov** [comment]
Nah, I think I'll just release it. Was asking to verify that I understood your use-case right.
