### ISSUE TITLE
Marker Clustering

### ISSUE THREAD

**Issue by sprocketc** [asennikov/ember-g-map#18]
I am implementing clustering support using [Marker-Clusterer](https://github.com/googlemaps/js-marker-clusterer).

I will create a pull request if you are interested. If not, i will publish a separate ember-addon that extends yours.

**Comment by asennikov** [comment]
This is very interesting project you have there!

I have nothing against adding it to this add-on as long as it'll be implemented as additional set of components using common marker components under the hood.

**Comment by sprocketc** [comment]
It will be implemented as such, but i will probably have to update the marker component `setMap` function to support clustering. I' ll see what i can do.
