### ISSUE TITLE
Open info window on 'mouseover'

### ISSUE THREAD

**Issue by movstox** [asennikov/ember-g-map#19]
Thanks for great plugin!

Would be great to open info window on mouse hover... Any ideas if that is possible? I can try submitting a PR, though need some help to start.

**Comment by asennikov** [comment]
Could be implemented as an option for `g-map-infowindow`, something like 
```
{{#g-map lat=37.7833 lng=-122.4167 zoom=12 as |context|}}
  {{g-map-marker context lat=37.7933 lng=-122.4167}}
  {{#g-map-marker context lat=37.7833 lng=-122.4267 as |markerContext|}}
    {{#g-map-infowindow openOn="hover" markerContext}}
      <h2>Bound Info Window</h2>
    {{/g-map-infowindow}}
  {{/g-map-marker}}
{{/g-map}}
```

In that case we'll need to alter this logic: https://github.com/asennikov/ember-g-map/blob/master/addon/components/g-map-infowindow.js#L102

I think I can work on it this coming weekend, but if you'd like to submit PR - it would be more than welcomed.

**Comment by movstox** [comment]
@asennikov thanks, i'll give it a try, though i'm new to all this frontend stuff. if no PR by Sat, then, probably, I've failed ;)

**Comment by asennikov** [comment]
Hey @movstox, on when do you think we should hide info window in that case? 

When mouse leaves marker? Because in that case if you have some interactive content in your info window it will be unreachable.

**Comment by movstox** [comment]
@asennikov I imagine it could work like this:

1) show on mouse over, hide on mouse out;
2) show on mouse click, don't hide on mouse out in this case;

**Comment by asennikov** [comment]
Just merged related PR, check it out - sorry for being so slow with that :snail:, hope you still need this feature.
