### ISSUE TITLE
No markers, no routes :(

### ISSUE THREAD

**Issue by Blackening999** [asennikov/ember-g-map#24]
Hello!

I just have tried your awesome library, however I don't see markers nor routes working :(
I tried with example from README.

What I'm doing wrong?

```js
ENV['g-map'] = {
    libraries: ['places', 'geometry', 'visualization', 'drawing'],
    key: '**key'
  }
```

```html
{{#g-map lat=37.7833 lng=-122.4167 zoom=12 as |context|}}
  {{g-map-marker context lat=37.7933 lng=-122.4167}}
  {{g-map-marker context lat=37.7833 lng=-122.4267 title=titleForSecondMarker}}
  {{g-map-marker context lat=37.7733 lng=-122.4067 label="3" title="Marker #3"}}
{{/g-map}}
```

**Comment by asennikov** [comment]
Hi, what ember version are you running?

**Comment by Blackening999** [comment]
Hey @asennikov 

Thanks for fast response!

2.2.0 (haven't upgraded to 2.3.0  yet)

**Comment by asennikov** [comment]
Hmm, 2.2.0 should be good. 
I'll try to replicate it in a clean repo and then let you know about results.

**Comment by Blackening999** [comment]
Thank you !

**Comment by Blackening999** [comment]
@asennikov 

It works after browser reload oO
Sorry for the mess, great library ;)

**Comment by asennikov** [comment]
:+1:
