### ISSUE TITLE
Cannot get markers to display

### ISSUE THREAD

**Issue by jrock2004** [asennikov/ember-g-map#28]
Using Ember 2.3.0. The map is showing the right area but I do not see the marker on the map

```
<div class="col-xs-12 col-md-8">
    {{#g-map lat=40.0403816 lng=-76.2205305 zoom=14 as |context|}}
        {{g-map-marker context lat=37.7933 lng=-122.4167 label="1" title="Locust Grove"}}
    {{/g-map}}
</div>
```

Now I have not added anything to the environment.js. Not sure if that is the reason

**Comment by asennikov** [comment]
Just tried your example:
- marker actually appears, however it appears outside your view area: (37.7933, -122.4167) is pretty far from (40.0403816, -76.220530);
- if you want your map to follow your added markers - use [these settings](https://github.com/asennikov/ember-g-map#map-fits-to-show-all-initial-markers) to setup fit-to-markers behaviour (however it's not perfect now with a single marker, as it will override your zoom settings, see this related issue https://github.com/asennikov/ember-g-map/issues/15).

**Comment by jrock2004** [comment]
I feel like an idiot. I see what I did. I set the zoom to where I wanted it, but inside I never updated the lat and long to match. Sorry for opening this

**Comment by asennikov** [comment]
np, I'm glad to help in any possible way
