### ISSUE TITLE
Map in a modal

### ISSUE THREAD

**Issue by rlb3** [asennikov/ember-g-map#31]
I'm trying to place the component in a bootstrap modal but the map shows only a gray rectangle when I open the model. I found a reason here: http://stackoverflow.com/questions/11742839/showing-a-google-map-in-a-modal-created-with-twitter-bootstrap.

It looks like I need to send the resize event to the map but I don't have a handle on the map. Is there anything I can do?

**Comment by asennikov** [comment]
Technically you can do this right.. It's not very user friendly though:

```
{{#g-map as |mapContext|}}
  {{your-custom-functional-component map=mapContext.map}}
  
  {{g-map-marker mapContext lat=lat lng=lng}}
{{/g-map}}
```

That way you can get `map` object in your component and send whatever events you would like.

I was thinking about adding special `service` to this addon to send events back to the map, but I haven't even started working on this improvement.
