### ISSUE TITLE
Possible to make markers draggable

### ISSUE THREAD

**Issue by stijn26** [asennikov/ember-g-map#33]
Hi,

Is it possible to make the markers draggable and get the latitude and longitude when dropped?

Because I prefer this addon over ember-cli-g-maps but I really need draggable markers.

**Comment by Mithrilhall** [comment]
@stijn26, could you close this issue since draggable markers have been added?

**Comment by asennikov** [comment]
I think I will go ahead and close it. 
@stijn26 feel free to reopen it if you want to discuss it more.
