### ISSUE TITLE
Programmatically zoom on marker / reset zoom level & point

### ISSUE THREAD

**Issue by Mithrilhall** [asennikov/ember-g-map#37]
How can I change the zoom level after programmatically opening an infoWindow on a marker?

Also, how would I go about resetting the zoom level and point?

Also, is this possible from outside the map component?

**Comment by asennikov** [comment]
You can just change your zoom property, which is bound to the map component. If you need to do that after opening infowindow, then change zoom after that. The same goes for lat/lng - you can update coordinates bound to the map and it will be applied on the map.

Add some more details if I don't get something.
