### ISSUE TITLE
Can I use custom markers?

### ISSUE THREAD

**Issue by jmccartie** [asennikov/ember-g-map#42]
I'm trying to use markers with custom colors. To do this in my current app (non-Ember), I'm doing this:

```javascript
function add_marker(item, point) {
  var pinImage = new google.maps.MarkerImage("https://chart.googleapis.com/chart?chst=d_map_pin_letter&chld=|" + item.iconcolor,
      new google.maps.Size(21, 34),
      new google.maps.Point(0,0),
      new google.maps.Point(10, 34));

  var marker = new google.maps.Marker({ map: map, position: point, clickable: true, icon: pinImage });
  return marker;
}
```

This sets a customer marker color. Any way to pass a pinImage when using `g-map-marker` ?

**Comment by asennikov** [comment]
Currently `{{g-map-marker}}` supports custom image files (jpg, png, svg, etc.) for icons, like:
```
{{g-map-marker context lat=lat lng=lng icon="/assets/images/driver-icon.svg" }}
```

But I think you may try binding your `pinImage` (instance of `google.maps.MarkerImage`) to the icon attribute of `{{g-map-marker}}`, it might actually work.

**Comment by jmccartie** [comment]
@asennikov Awesome, thanks! Should I add that info to the README?

**Comment by asennikov** [comment]
Yeah, would be nice!
