### ISSUE TITLE
What is the correct nesting for g-map-infowindow?

### ISSUE THREAD

**Issue by josephh** [asennikov/ember-g-map#49]
Trying the example template code on the readme section, **Marker bound to address query**, the browser doesn't seem to like g-map-infowindow being nested in the g-map-address-marker block.
The error in the browser console is, 
`Uncaught Error: Assertion Failed: Must be inside {{#g-map}} or {{#g-map-marker}} components with context set`

**Comment by asennikov** [comment]
whoops, there was an issue in readme - missing ` as |markerContext|` part:
```handlebars
{{#g-map lat=37.7833 lng=-122.4167 zoom=12 as |context|}}
  {{#g-map-address-marker context address="Delft, The Netherlands" as |markerContext|}}
    {{#g-map-infowindow markerContext}}
      Works in block form too.
    {{/g-map-infowindow}}
  {{/g-map-address-marker}}
{{/g-map}}
```

**Comment by josephh** [comment]
😄

**Comment by josephh** [comment]
For the same example code in the readme, the double click event works nicely - info window shows - but not the single click or the mouse over.  If I comment out the second two **g-map-marker**s then the mouseover has the desired effect and I see the info window with expected text.

**Comment by asennikov** [comment]
could you post a code sample here?

**Comment by josephh** [comment]
I'm copying and pasting your examples into a handlebars template.  My experience is that only the last openOn action applies.  Commenting out the dblClick onClick for me (as below) gets the single click onClick working.  I'm running 
`ember --version
version: 2.4.2
node: 4.4.0
os: darwin x64`

```javascript 
<div class="row">
  <div class="col-md-6 panel panel-default panel-body">
    <h4>Details</h4>
    <ul>
      <li>
        <strong>Location</strong>
        <ul>
          <li>
            <strong>Name</strong>{{input value=name}}
          </li>
          <li>
            {{#g-map lat=37.7833 lng=-122.4167 zoom=12 as |context|}}
              {{#g-map-marker context lat=37.7833 lng=-122.4267 as |markerContext|}}
                {{#g-map-infowindow markerContext openOn="mouseover" closeOn="mouseout"}}
                  <h2>Bound Info Window</h2>
                {{/g-map-infowindow}}
              {{/g-map-marker}}
              {{#g-map-marker context lat=37.7833 lng=-122.4267 as |markerContext|}}
                {{g-map-infowindow markerContext openOn="click" closeOn="click" title="Blockless form 1"}}
              {{/g-map-marker}}
              <!-- {{#g-map-marker context lat=37.7833 lng=-122.4267 as |markerContext|}}
                {{g-map-infowindow markerContext openOn="dblclick" title="Blockless form 2"}}
              {{/g-map-marker}} -->
            {{/g-map}}
          </li>
        </ul>
      </li>
    </ul>
  </div>
</div>
`

**Comment by asennikov** [comment]
Isn't it because all 3 markers have the same coordinates? So they overlap with each other and you see only the last one? Try spreading them around a bit and tell me if it works :)

**Comment by asennikov** [comment]
I'm closing this for now, but fill free to reach me if you still have any issues.
