### ISSUE TITLE
Possible to do KML layers?

### ISSUE THREAD

**Issue by mklnz** [asennikov/ember-g-map#50]
I'm wondering how to do KML layers using this addon?
https://developers.google.com/maps/documentation/javascript/examples/layer-kml

Perhaps using just some plaun javascript for now?

**Comment by asennikov** [comment]
so yeah, we don't have support for that feature yet, but you can do it in some hacky way with custom "functional" components:

```handlebars
{{#g-map lat=lat lng=lng zoom=13 as |mapContext|
  {{your-kml-component map=mapContext.map kmlUrl="http://example.com/layer.kml}}
{{/g-map}}
```

and then `your-kml-component` component could be something like:
```javascript
import Ember from 'ember';

export default Ember.Component.extend({
  init() {
    this._super(...arguments);
    this.setKmlLayer();
  },
  mapHasBeenSet: Ember.observer('map', function() {
    Ember.run.once(this, 'setKmlLayer');
  }),
  setKmlLayer() {
    const map = this.get('map');
    const url = this.get('kmlUrl');

    if (Ember.isPresent(map) && Ember.isPresent(url)) {
      const layer = new google.maps.KmlLayer({ url, map });
      this.set('layer', layer);
    }
  }
});
```

**Comment by asennikov** [comment]
also looks like this feature could be added really easy, so if you can make it work maybe you can consider contributing to the project by adding `{{g-map-kml-layer}}` component 😃

**Comment by mklnz** [comment]
@asennikov Great, thanks for the tip. I will give it a try and see how I go.
