### ISSUE TITLE
Display Location

### ISSUE THREAD

**Issue by smitakiran25** [asennikov/ember-g-map#53]
I am trying to popup location and near by hospitals in a g-map 

![image](https://cloud.githubusercontent.com/assets/11611902/15651508/be17b7bc-269d-11e6-8a92-1317d651beb3.png)

![image](https://cloud.githubusercontent.com/assets/11611902/15651622/5e8b3bec-269e-11e6-9c60-9f46119b340c.png)

when i click on the submit button on the above form after entering location. The enterd location should  be display In the g-map and also display near by hospitals with icon.

i am not getting how to display  entered location and hospitals.in a g-map

**Comment by asennikov** [comment]
Hi @smitakiran25, it's pretty hard to help you by only seeing screenshot, some code snippets could be handy here.
But anyway, let me try.

Assuming that your form component is something like:

```javascript
// my-pretty-form-component.js
import Ember from 'ember';

export default Ember.Component.extend({
  actions: {
    submit() {
      if (Ember.isPresent(this.get('location'))) {
        this.set('mapIsShown', true);
        // also search for nearby hospitals (that's on your side)
        // I assume that you set them in `nearbyHospitals` property
      }
    },
    cancel() {
      // whatever
    }
  }
});
```

and its template:
```handlebars
{{!-- my-pretty-form-component.hbs --}}

<form>
  Location {{input value=location}}
  <button {{action "submit"}}> Submit </button>
  <button {{action "cancel"}}> Cancel </button>
</form>
```

To show markers just add this to the end of your template:

```handlebars
{{#if mapIsShown}}
  {{#g-map markersFitMode='live' as |context|}}
    {{g-map-address-marker context address=location}}
    
    {{#each nearbyHospitals as |hospital|}}
      {{g-map-marker context lat=hospital.lat lng=hospital.lng icon="/assets/images/hospital-icon.svg" }}
    {{/each}}
  {{/g-map}}
{{/if}}
```

**Comment by smitakiran25** [comment]
I tried on that but i am not getting 
 app/template/newcase.hbs
<nav class="navbar navbar-default navbar-pf" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

      </div>
      <div class="collapse navbar-collapse navbar-collapse-1">

        <ul class="nav navbar-nav navbar-primary">

               <a class="navbar-brand" href="/">
       Rescue Management
        </a>
        </ul>

           <ul class="nav navbar-nav navbar-utility">

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="pficon pficon-user"></span>
             UserName <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <a href="#">Logout</a>
              </li>
              <li>
                <a href="#">Settings</a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
      <hr>

    <nav class="navbar navbar-default navbar" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

      </div>
      <div class="collapse navbar-collapse navbar-collapse-1">

       <ul class="nav navbar-nav navbar-primary">

         <li>
         {{#link-to 'newcase' }}
          <b> New Case</b>
          {{/link-to}}
       </li>
      <li>
     {{#link-to 'gmap' }}
      <b>Gmap</b>
      {{/link-to}}
    </li>
        </ul>
      </div>
    </nav>
 <div class="container-fluid" id="enquiry">
      <div class="row">
        <div class="col-sm-9 col-md-10">
          <div class="col-sm-12 col-md-6">
            <form class="form-horizontal">

              <div class="form-group">
                <label class="col-md-4 control-label" for="textInput2">Location</label>
                <div class="col-md-8">
                  {{input type="text" class="form-control" value=location}}
                </div>
              </div>

              <div class="form-group">
     <label class="col-md-4 control-label" for="textInput2"></label>
       <div class="col-md-8">
      <button {{action 'addCase' model.id}} type="button" class="btn btn-primary">Submit</button>
      <button type="button" class="btn btn-default">Cancel</button>
    </div>
  </div>
</form>
</div>
</div>
</div>
</div>

app/route/newcase.js
import Ember from 'ember';

export default Ember.Route.extend({
  model: function() {
    return this.get('store').findAll('case');
  }
});

app/controller/newcase.js
import Ember from 'ember';

export default Ember.Controller.extend({
  actions:{
    addCase: function() {
      var location = this.get('location');


     var newCase = this.store.createRecord('case', {
       location : location
     });

    newCase.save();

  this.setProperties({
    location: ' ',

  });
  }
 }
});

app/model/case.js
import Model from 'ember-data/model';
import attr from 'ember-data/attr';

export default Model.extend({
    location: attr('string')

});

import Ember from 'ember';

export default Ember.Component.extend({
  actions: {
    submit() {
      if (Ember.isPresent(this.get('case.location'))) {
        this.set('mapIsShown', true);
      }
    },
  }
});

app/components/newcase.js

import Ember from 'ember';

export default Ember.Component.extend({
  actions: {
    submit() {
      if (Ember.isPresent(this.get('case.location'))) {
        this.set('mapIsShown', true);
      }
    },
  }
});

app/template/gmap/hbs
<h2 id="title">Ember-g-map Component</h2>

<form {{action "updateAdressQuery" on="submit"}}>
  <p>
    <label>Address Query for Bound Marker</label>
    {{input value=addressQueryInput}}
  </p>
</form>

{{#g-map markersFitMode="live" options=customOptions as |context|}}

  {{#g-map-polyline context strokeColor="green" strokeWeight="10" strokeOpacity="0.3" as |coordinateContext|}}
  {{/g-map-polyline}}

  {{g-map-marker context lat=12.9787 lng=77.5724}}

  {{#g-map-marker context lat=37.7433 lng=-122.3867 as |markerContext|}}
  {{/g-map-marker}}

    {{#if mapIsShown}}
    {{#g-map markersFitMode='live' as |context|}}
      {{g-map-address-marker context address=location}}

        {{#each nearbyHospitals as |hospital|}}
          {{g-map-marker context lat=hospital.lat lng=hospital.lng icon="/assets/images/hospital-icon.svg" }}
        {{/each}}
      {{/g-map}}
    {{/if}}
{{/g-map}}

app/controller/gmap.js
import Ember from 'ember';

const { computed } = Ember;

export default Ember.Controller.extend({
  randomVariable: 111,

  addressQuery: 'SF, Lafayette Park',
  addressQueryInput: computed.reads('addressQuery'),
  routeColor: 'red',
  showingAllPolylineCoords: true,

  customOptions: computed(function() {
    if (google) {
      return { mapTypeId: google.maps.MapTypeId.TERRAIN };
    }
  }),

  actions: {
    refresh() {
      this.set('randomVariable', Math.floor(Math.random() * 1000));
    },

    onInfowindowClosed() {
      window.alert('Info Window Closed!');
    },

    updateAdressQuery() {
      this.set('addressQuery', this.get('addressQueryInput'));
    },

    toggleRouteColor() {
      if (this.get('routeColor') === 'red') {
        this.set('routeColor', 'green');
      } else {
        this.set('routeColor', 'red');
      }
    },

    togglePolylineCoords() {
      this.toggleProperty('showingAllPolylineCoords');
    }
  }
});

please tel me how to display location and near by hospitals and how to add lat,lang of each hospitals

**Comment by asennikov** [comment]
Sorry, I can't really understand what you're trying to show me here... Could you structure those code pieces a little bit? Something like:

file1.js
```javascript
its content
its content
its content
```

file2.hbs
```handlebars
its content
its content
its content
```

...
etc.

**Comment by smitakiran25** [comment]
Ok sir sorry for that, i had sent the screen shots of hbs and js files

**app/template/newcase.hbs**
![image](https://cloud.githubusercontent.com/assets/11611902/16143181/b8b960ba-3488-11e6-9935-91be3a52db46.png)


**app/controller/newcase.js**
![image](https://cloud.githubusercontent.com/assets/11611902/16143194/de1ec0d4-3488-11e6-94a7-1991550ee26d.png)

 
**app/template/gmap.hbs**
![image](https://cloud.githubusercontent.com/assets/11611902/16143209/f7cfa534-3488-11e6-8499-ad83b9c0c4d3.png)

 
**app/controller/gmap.js**

![image](https://cloud.githubusercontent.com/assets/11611902/16143221/12218754-3489-11e6-82dc-b202f3a3cca4.png)

**app/component/newcase,js**
![image](https://cloud.githubusercontent.com/assets/11611902/16143259/48475ec6-3489-11e6-9527-ef1adbaa8c80.png)

**app/model/case.js**
![image](https://cloud.githubusercontent.com/assets/11611902/16143271/5e5bed94-3489-11e6-9851-eaa9a46b94ac.png)



**app/route/newcase.js**
![image](https://cloud.githubusercontent.com/assets/11611902/16143319/9b30230c-3489-11e6-8872-79aabf80e2d4.png)


**app/router.js**
![image](https://cloud.githubusercontent.com/assets/11611902/16143334/b04811be-3489-11e6-9101-e837d8b8ddf8.png)

**Comment by smitakiran25** [comment]
I tried to work on that i changed **app/template/newcase.hbs** to **app/template/component/new-case.hbs**

![image](https://cloud.githubusercontent.com/assets/11611902/16170363/de81b5f0-356d-11e6-9dc1-b6e6d61d244f.png)


**app/template/index.hbs**

{{new-case}}

i am getting following error 
ember.debug.js:40998Uncaught Error: <google-route@component:new-case::ember368> had no action handler for: addCase

**Comment by steveszc** [comment]
Closing. This looked like an implementation issue, not an issue with the addon.
