### ISSUE TITLE
Setting default map type

### ISSUE THREAD

**Issue by nabihahossain** [asennikov/ember-g-map#54]
How do I set the map type to satellite by default? I understand there are custom options you can configure, but I'm not sure about its exact location and syntax.

**Comment by Mithrilhall** [comment]
I can't promise this is the correct way but:

route.js:
```
model: function () {

		var customOptions = {
			mapTypeId: google.maps.MapTypeId.SATELLITE
		};

		return Ember.RSVP.hash({
      		markers: ...,
      		customOptions: customOptions
		});
```

template.hbs:
`{{custom-map model=markers customOptions=customOptions}}`

custom-map component template:
```
{{#g-map id="map" options=customOptions markersFitMode='live' as |context|}}
{{/g-map}}
```

**Comment by asennikov** [comment]
yes, @Mithrilhall is right, just create a custom options object wherever you want and feed it to `g-map` component.

**Comment by Mithrilhall** [comment]
@nabihahossain or @asennikov; could one of you close this issue?
