### ISSUE TITLE
Question: Are there onClick handlers for the map itself?

### ISSUE THREAD

**Issue by jstoup111** [asennikov/ember-g-map#55]
See question

**Comment by asennikov** [comment]
no, we do not support map event directly yet. But you can use a workaround using additional functional component:

```handlebars
{{#g-map lat=lat lng=lng zoom=zoom as |mapContext|}}
  {{your-event-component map=mapContext.map onClick=(action "yourOnClickHandler")}}

  {{!-- ... your markers and other map stuff --}}
{{/g-map}}
```

whereas `your-event-component` component is:

```javascript
import Ember from 'ember';
/* global google */

export default Ember.Component.extend({
  didInsertElement() {
    this._super(...arguments);
    const map = this.get('map');
    google.maps.event.addListener(map,'click', (eventData) => {
      this.attrs.onClick(eventData);
    });
  }
});
```

this will call `yourOnClickHandler` of your parent component/controller/route.

Also, if it something interesting to you - you can try taking over this https://github.com/asennikov/ember-g-map/pull/29 PR. It implements support for map events, but was abandoned some time ago.
