### ISSUE TITLE
g-map-address-route fails in component integration test due to calling set on a destroyed component

### ISSUE THREAD

**Issue by arthur5005** [asennikov/ember-g-map#59]
Using this component can easily cause a parent component integration test to fail.

This is due to the Places api callback trying to call set on the destroyed component, in this case: `g-map-address-route` 

Just create a bare component, put a gmap inside it and then a g-map-address-route:

```
{{#g-map
    markersFitMode='live'
    as |context|}}
  {{g-map-address-route context
    originAddress="Some address 1"
    destinationAddress="Some address 2"
  }}
{{/g-map}}
```

Run the integration test.

This also causes issues when quickly opening and closing a pane which contains one of these, since the component destroys before the places api returns.

**Comment by asennikov** [comment]
Good catch! I think we can add a check there for object being destroyed. Wanna make a PR?
