### ISSUE TITLE
Open infowindow programatically

### ISSUE THREAD

**Issue by Juraci** [asennikov/ember-g-map#60]
I'm in a situation where I have a sidebar and the map displayed in the main area. I would like to open a given marker infowindow whenever I click in one of the items in the  sidebar.  Is it possible to create an action that programmatically opens the infowindow of a given marker context?

**Comment by Mithrilhall** [comment]
@Juraci https://github.com/asennikov/ember-g-map/issues/34

**Comment by Mithrilhall** [comment]
@Juraci, do you have an example in github?

**Comment by Juraci** [comment]
@Mithrilhall yes I do have.

Given this template which has a sidebar and the main area which displays the map:
```handlebars
<div id='sidebar-wrapper'>
    <div class='property' {{action 'showOnMap' on='mouseEnter'}}>
        <img src='some-image'>
        <p class='address'>Some Cool Property Address</p>
    </div>
</div>
<div id='map-wrapper'>
    {{#g-map markersFitMode='live' as |context|}}
        {{#g-map-marker context lat=-30.041548 lng=-51.217107 title='Home' as |markerContext|}}
            {{#g-map-infowindow markerContext openOn="mouseover" closeOn="mouseout"}}
                <img id='marker-image' src='some-image'>
            {{/g-map-infowindow}}
        {{/g-map-marker}}
    {{/g-map}}
</div>
```

I would like that the showOnMap action on the `.property` element on the sidebar to programmatically trigger the infowindow.open() on the bounded marker:

```javascript
import Ember from 'ember';

export default Ember.Route.extend({
    actions: {
        showOnMap() {
            Ember.Logger.warn('Mouseenter');
            // Somehow trigger infowindow.open() for the marker context in the map
        }
    }
});
``` 

Here is the entire project: https://github.com/Juraci/sky-watcher

**Comment by Mithrilhall** [comment]
@Juraci - I used an [Event Bus](http://www.thesoftwaresimpleton.com/blog/2015/04/27/event-bus/) to pass around the map context. I'm not sure if this is the best way but that's how I ended up getting it to work.

I'll try to get your project working with it.

**Comment by Juraci** [comment]
@Mithrilhall cool I will take a look on this Event Bus too, the solution I've come up with was to render the infowindow by default:

ember-g-map/addon/components/g-map-infowindow.js
```javascript
didRender() {
    this.open();
}
```

probably this is not the best way but now I can hide/show the infowindow with conditional statements in the handlebars.

**Comment by asennikov** [comment]
I have another idea how to implement that:

1) your template, notice the addition of the `{{infowindow-trigger}}` component
```handlebars
<div id='sidebar-wrapper'>
    <div class='property' {{action 'showOnMap' on='mouseEnter'}}>
        <img src='some-image'>
        <p class='address'>Some Cool Property Address</p>
    </div>
</div>
<div id='map-wrapper'>
    {{#g-map markersFitMode='live' as |context|}}
        {{#g-map-marker context lat=-30.041548 lng=-51.217107 title='Home' as |markerContext|}}
            {{infowindow-trigger infowindow=markerContext.infowindow}}
            {{#g-map-infowindow markerContext openOn="mouseover" closeOn="mouseout"}}
                <img id='marker-image' src='some-image'>
            {{/g-map-infowindow}}
        {{/g-map-marker}}
    {{/g-map}}
</div>
```

2) to tie everything together we may use a service, let's call it `services/infowindow-trigger.js`:
```javascript
import Ember from 'ember';

const { isPresent } = Ember;

export default Ember.Service.extend({
    show() {
        const infowindow = this.get('infowindow');
        if (isPresent(infowindow)) {
            infowindow.open();
        }
    }
});
```

3) then that additional component `components/infowindow-trigger.js` gonna just setup our service with infowindow, received from marker context:
```javascript
import Ember from 'ember';

const { inject, observer, run } = Ember;

export default Ember.Component.extend({
    infowindowTrigger: inject.service(),

    init() {
        this._super(...arguments);
        this.setUpInfowindow();
    }, 

    infowindowChanged: observer('infowindow', function() {
        run.once(this, 'setUpInfowindow');
    }),

    setUpInfowindow() {
        this.set('infowindowTrigger.infowindow', this.get('infowindow'));
    }
});
```

4) and after all that happened, we can use that service in route or wherever else in app:
```javascript
import Ember from 'ember';

export default Ember.Route.extend({
    infowindowTrigger: inject.service(),

    actions: {
        showOnMap() {
            Ember.Logger.warn('Mouseenter');
            this.get('infowindowTrigger').show();
        }
    }
});
```
