### ISSUE TITLE
Add polygons

### ISSUE THREAD

**Issue by hbrysiewicz** [asennikov/ember-g-map#62]
I noticed this was listed on the README as a desired feature request. It also is something that `ember-cli-g-maps` was covered for. I would like to potentially work on implementing this.

**Comment by asennikov** [comment]
Yes, that shouldn't be too hard to add them, we already have polylines, polygons are basically the same, with a few more params.
If you have enough time - please submit PR, if not I can look into it myself in coming weeks.

**Comment by steveszc** [comment]
closing in favor of #101
