### ISSUE TITLE
[Feature request] DrawManager component

### ISSUE THREAD

**Issue by hbrysiewicz** [asennikov/ember-g-map#63]
I've done some work with the `DrawManager` with the google maps api directly but think it would be nice to have it emberized within this component. I would potentially like to work on this feature.

**Comment by asennikov** [comment]
That sounds awesome! I can help you as much as I can to integrate that functionality here. However, I need to read docs a little bit to see how it could be best implemented. 

Also, I'm not sure yet, but it may make sense to have it as an additional `ember-g-map-draw-manager` plugin-addon which brings DrawManager functionality and components. Something similar to what ember-cli-deploy has with their ecosystem of plugins. 
In any case, let me know what you think.

**Comment by GCorbel** [comment]
I there any update on this ?

**Comment by steveszc** [comment]
This would be a good candidate to be implemented as a separate addon designed to be used within an `ember-g-map`.
