### ISSUE TITLE
When I refresh a page with the mouse the map get an invalid key

### ISSUE THREAD

**Issue by alvarouribe** [asennikov/ember-g-map#64]
Google Maps API error: MissingKeyMapError 

my config/environ... looks like this 
  ENV['g-map'] = {
    libraries: ['drawing'],
    client: 'gme-...'
  }

is it a bug or what?

Cheers

**Comment by Mithrilhall** [comment]
@alvarouribe Do you have a key?

```
ENV['g-map'] = {
        libraries: ['places', 'geometry'],
        key: 'DYBXa-AP2buA14zxCWGT4izpD5aIBysdHWS3yMuw0ry',
        protocol: 'https',
        libraries: ['places']
    };
```

**Comment by alvarouribe** [comment]
Hi no I just have the client because I am using the client id from my company

**Comment by steveszc** [comment]
@alvarouribe The addon isn't set up to handle client IDs right now, I ran in to the same problem. I just opened PR #67 that adds `client` as an optional config param.

**Comment by Mithrilhall** [comment]
@alvarouribe, could you close this issue since this feature has been added?

**Comment by asennikov** [comment]
Closing the issue, if you guys have anything else to add here - feel free to reopen it.
