### ISSUE TITLE
Complex Marker Icons error

### ISSUE THREAD

**Issue by alvarouribe** [asennikov/ember-g-map#74]
When I implement this 
	openIcon: {
		url: "/assets/images/pin-icon_open.svg",
		size: new google.maps.size(30,30),
		scaledSize: new google.maps.size(20,20),
		anchor: new google.maps.point(15, 15),
		origin: new google.maps.point(0, 0),
		labelOrigin: new google.maps.point(30, 15)
	},

I get  Uncaught TypeError: google.maps.size is not a constructor

It seams that I am missing an import...

**Comment by jeffrey008** [comment]
Hello, can you please provide more code, like hbs, to debug this problem?
Also please `use display code` to improve readability.
Like this:
``` javascript
openIcon: {
url: "/assets/images/pin-icon_open.svg",
size: new google.maps.size(30,30),
scaledSize: new google.maps.size(20,20),
anchor: new google.maps.point(15, 15),
origin: new google.maps.point(0, 0),
labelOrigin: new google.maps.point(30, 15)
},
```

**Comment by alvarouribe** [comment]
Sure I create the whole thing here:
https://github.com/alvarouribe/ember-map-test
just add your id for the map in config/environment

this are the errors on ember-cli

controllers/application.js: line 6, col 15, 'google' is not defined.
controllers/application.js: line 7, col 21, 'google' is not defined.
controllers/application.js: line 8, col 17, 'google' is not defined.
controllers/application.js: line 9, col 17, 'google' is not defined.
controllers/application.js: line 10, col 22, 'google' is not defined.

**Comment by jeffrey008** [comment]
Hi there. I have figured it out. You just need to capital everything after `google.map`. Here is how this works.
```javascript
  myIcon: {
    url: "/assets/images/logo.png",
    size: new google.maps.Size(30,30),
    scaledSize: new google.maps.Size(20,20),
    anchor: new google.maps.Point(15, 15),
    origin: new google.maps.Point(0, 0),
    labelOrigin: new google.maps.Point(30, 15)
  },
```
If you add a breakpoint in the controller and console 'google' to see what's inside, you will see that everything in there are capitalised.

So I think there is a typo in the readme file, we gotta need to fix that or else more people will have the same problem.

**Comment by alvarouribe** [comment]
Awesome that worked !!!
