### ISSUE TITLE
enable setting map options?

### ISSUE THREAD

**Issue by awwester** [asennikov/ember-g-map#8]
I'm wanting to set `scrollwheel: false` but am not seeing any way to set these options. Is this something that is already included that I'm missing, or is it a possibility for an enhancement? 
http://stackoverflow.com/a/2330272/2548934

**Comment by asennikov** [comment]
Yeah, it's actually the next thing I was planning to work on. So, there's a good chance I'll add parameter to set custom map options this weekend.

**Comment by asennikov** [comment]
Added in https://github.com/asennikov/ember-g-map/pull/9
