### ISSUE TITLE
Advanced marker issue?

### ISSUE THREAD

**Issue by briancwald** [asennikov/ember-g-map#83]
I am having an issue using the advanced marker, but I am not sure how to troubleshoot. 

Using the standard icon="path/to/img" works fine. 

When I use the example of the advanced marker, I know the object is being read on map render, but nothing changes and there are no errors (added a stop in the console inside the object). It feels like I am missing something, Is there an import I need to do in my controller/route?

Im using Ember 2.8

**Comment by jeffrey008** [comment]
Hello, can you provide some code or a simple project in [https://ember-twiddle.com/](https://ember-twiddle.com/) to demonstrate your problem?
This allow us to debug your code and investigate on it. Thanks

**Comment by steveszc** [comment]
Closing, awaiting response. Can re-open if we get a reproduction.
