### ISSUE TITLE
Question: Is it possible to ADD a marker on click?

### ISSUE THREAD

**Issue by desmond1303** [asennikov/ember-g-map#86]
I've read through the documentation, but i didn't see any onClick events on the map itself. I'd want to be able to add new markers to the map with a click? Is that possible ?

**Comment by asennikov** [comment]
Nope, there's no such option yet. However, this sounds like an easy one - we can add it. Feel free to submit a PR if you happen to be in opensource mood.

**Comment by asennikov** [comment]
Also, it is possible to use a bit of manual interaction with Google Map to achieve that:

```
{{#g-map as |mapContext|}}
  {{your-click-listener-component map=mapContext.map onClick=(action "onNewMarker")}}
{{/g-map}}
```

and in `your-click-listener-component/component.js` you may have:

```
import Ember from 'ember';

export default Ember.Component.extend({
    init() {
        this._super(...arguments);
        this.setupListener();
    }, 

    setupListener() {
        const map = this.get('map');
        map.addListener('click', (event) => this.handleClick(event));
    },

    handleClick(event) {
      const lat = event.latLng.lat();
      const lng = event.latLng.lng();
      this.attrs.onClick(lat, lng);
    }
});
```

**Comment by bonroyage** [comment]
Using your sample code above, the map variable always returns an `undefined` value for me. So to make it work I passed the `mapContext` rather than the `mapContext.map` in the handlebars template and called `setupListener` in an `observer` instead of the `init` function

```hbs
{{#g-map as |mapContext|}}
  {{your-click-listener-component mapContext=mapContext onClick=(action "onNewMarker")}}
{{/g-map}}
```

```js
// ...
map : Ember.computed.alias('mapContext.map'),

mapWasSet : Ember.observer('map', function () {
    this.setupListener();
}),
// ...
```
