### ISSUE TITLE
Reference map object from within controller?

### ISSUE THREAD

**Issue by ImJacobChen** [asennikov/ember-g-map#88]
Hi there,

Just wondering if you would know how to reference the `map` object from within a controller?

So I can use code like `service = new google.maps.places.PlacesService(map);` and `map.getBounds()`

Many Thanks!

Jacob

Also I am not sure if this is the right place to be asking questions but worth a try

**Comment by steveszc** [comment]
Eventually we'll probably move the map itself into a service which would make this trivial.

If you're just trying to instantiate a PlacesService you can just pass in a dom node like so `google.maps.places.PlacesService(document.createElement('div'))`.
https://developers.google.com/maps/documentation/javascript/3.exp/reference#PlacesService

For other use cases where you really do need access to the map from the outside you'd probably need to create your own component that would handle setting the map on the controller via an action.

```
import Ember from 'ember';
export default Ember.Controller.extend({
  map: null,
  mapBounds: Ember.computed('map', function() {
    return map ? map.getBounds() : null;
  }),
  actions: {
    setMap(map) {
      this.set('map', map);
    }
  }
});
```

```
{{#g-map lat=lat lng=lng as |mapContext|}}
  {{g-map-accessor mapContext setMap=(action 'setMap')}}
{{/g-map}}
```

```
import Ember from 'ember';
const GMapAccessor = Ember.Component.extend({
  mapWasSet: Ember.observer('mapContext.map', function() {
    Ember.run.once(this, function() {
     this.get('setMap')(this.get('mapContext.map'));
    });
  })
});
GMapAccessor.reopenClass({
  positionalParams: ['mapContext']
});
export default GMapAccessor;
```
