### ISSUE TITLE
Cap on the number of routes?

### ISSUE THREAD

**Issue by joegaudet** [asennikov/ember-g-map#92]
First off, thanks so much for your work on this addon, we are loving using it.

I've noticed at most I'm only able to show 3 routes at a time. Is this an imposed limitation? Or am I doing something wrong?

```
    {{#g-map markersFitMode='live'
             classNames='fde-logistics-planning_gmap'
             options=customOptions as |context|}}
      {{#each driverAllocations as |driverAllocation|}}
          {{g-map-address-route context
                                travelMode='driving'
                                strokeColor=driverAllocation.color
                                strokeWeight=(ternary (eq order selectedOrder) '5' '3')

                                originAddress=order.restaurantLocation.gmapsAddress
                                destinationAddress=order.clientLocation.gmapsAddress
          }}
      {{/each}}
    {{/g-map}}
```

We've got a paid gmaps key, is it perhaps a question of rate limiting?

**Comment by steveszc** [comment]
Did you ever resolve this issue @joegaudet?

This shouldn't be a rate limit issues according to https://developers.google.com/maps/documentation/javascript/directions#UsageLimits

If you can throw this up on a Twiddle I'd be happy to take a look.
