### ISSUE TITLE
add event based on g-map / {{g-map}}

### ISSUE THREAD

**Issue by cahyowhy** [asennikov/ember-g-map#93]
how to add event on g-map. i just wanna get lat lng when user click the map

**Comment by steveszc** [comment]
You'll need to make a component that can be placed inside the g-map block to handle whatever custom behavior you need. See https://github.com/asennikov/ember-g-map/issues/86 for example.

**Comment by steveszc** [comment]
Also see https://github.com/asennikov/ember-g-map/issues/55 for another example of how to do this
